In [35]:
import pandas as pd

In [36]:
data=pd.read_csv('car data.csv')
data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [37]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

data['Fuel_Type'] = encoder.fit_transform(data['Fuel_Type'])
data['Seller_Type'] = encoder.fit_transform(data['Seller_Type'])
data['Transmission'] = encoder.fit_transform(data['Transmission'])
data['Car_Name'] = encoder.fit_transform(data['Car_Name'])

In [38]:
print(data.dtypes)

Car_Name           int64
Year               int64
Selling_Price    float64
Present_Price    float64
Kms_Driven         int64
Fuel_Type          int64
Seller_Type        int64
Transmission       int64
Owner              int64
dtype: object

In [39]:
x=data.drop('Selling_Price',axis=1)
x

,Car_Name,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,90,2014,5.59,27000,2,0,1,0
1,93,2013,9.54,43000,1,0,1,0
2,68,2017,9.85,6900,2,0,1,0
3,96,2011,4.15,5200,2,0,1,0
4,92,2014,6.87,42450,1,0,1,0
...,...,...,...,...,...,...,...,...
296,69,2016,11.60,33988,1,0,1,0
297,66,2015,5.90,60000,2,0,1,0
298,69,2009,11.00,87934,2,0,1,0
299,69,2017,12.50,9000,1,0,1,0
300,66,2016,5.90,5464,2,0,1,0

In [40]:
y=data['Selling_Price']
y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [41]:
y.value_counts()

Selling_Price
0.45     8
0.60     8
4.50     7
5.25     7
4.75     6
        ..
10.11    1
6.40     1
8.55     1
9.50     1
11.50    1
Name: count, Length: 156, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

In [44]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,root_mean_squared_error

In [45]:
lr=LinearRegression()

In [46]:
lr.fit(x_train,y_train)

LinearRegression()

In [47]:
train_pred=lr.predict(x_train)
train_mse=mean_squared_error(y_train,train_pred)
print('mean_squared_error on training=',train_mse)

mean_squared_error on training= 2.681800526871402

In [48]:
test_pred=lr.predict(x_test)
test_mse=mean_squared_error(y_test,test_pred)
print('mean_squared_error on testing=',test_mse)

mean_squared_error on testing= 8.82494984048389

In [49]:
mae=mean_absolute_error(y_test,test_pred)

In [50]:
print('mean_absolute_error=',mae)

mean_absolute_error= 1.504977658178586

In [51]:
rmse=root_mean_squared_error(y_test,test_pred)

In [52]:
print('root_mean_squared_error=',rmse)

root_mean_squared_error= 2.97068171308942

In [53]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score,mean_squared_error,mean_absolute_error,r2_score

In [54]:
rf = RandomForestRegressor()

In [55]:
rf.fit(x_train,y_train)

RandomForestRegressor()

In [56]:
y_pred = rf.predict(x_test)
mae = mean_absolute_error(y_test,y_pred)
print("MAE:",mae)

MAE: 0.8039131147540982

In [57]:
mse = mean_squared_error(y_test,y_pred)
print("MSE:",mse)

MSE: 6.38429812147541

In [58]:
r2 = r2_score(y_test,y_pred)
print("R2 Score:",r2)

R2 Score: 0.8284392933244351