#Data  Preprocessing

In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_csv("IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
df.shape

(50000, 2)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [5]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(418)

In [8]:
df.drop_duplicates(inplace=True)
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [9]:
df["review"] = df["review"].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [10]:
df["review"] = df["review"].apply(
    lambda x: re.sub(r'[^\w\s]', '', x)
)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [11]:
df["review"] = df["review"].astype(str)

df["review"] = df["review"].apply(lambda x: x.split())

df["review"]

0        [one, of, the, other, reviewers, has, mentione...
1        [a, wonderful, little, production, br, br, the...
2        [i, thought, this, was, a, wonderful, way, to,...
3        [basically, theres, a, family, where, a, littl...
4        [petter, matteis, love, in, the, time, of, mon...
                               ...
49995    [i, thought, this, movie, did, a, down, right,...
49996    [bad, plot, bad, dialogue, bad, acting, idioti...
49997    [i, am, a, catholic, taught, in, parochial, el...
49998    [im, going, to, have, to, disagree, with, the,...
49999    [no, one, expects, the, star, trek, movies, to...
Name: review, Length: 49582, dtype: object

In [12]:
from nltk.corpus import stopwords

In [13]:
stop_words = set(stopwords.words("english"))

In [14]:
df["review"] = df["review"].apply(
    lambda x: [word for word in x if word not in stop_words]
)
df

                                                  review sentiment
0      [one, reviewers, mentioned, watching, 1, oz, e...  positive
1      [wonderful, little, production, br, br, filmin...  positive
2      [thought, wonderful, way, spend, time, hot, su...  positive
3      [basically, theres, family, little, boy, jake,...  negative
4      [petter, matteis, love, time, money, visually,...  positive
...                                                  ...       ...
49995  [thought, movie, right, good, job, wasnt, crea...  positive
49996  [bad, plot, bad, dialogue, bad, acting, idioti...  negative
49997  [catholic, taught, parochial, elementary, scho...  negative
49998  [im, going, disagree, previous, comment, side,...  negative
49999  [one, expects, star, trek, movies, high, art, ...  negative

[49582 rows x 2 columns]

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X = df["review"]
y = df["sentiment"]

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [18]:
X_train.shape

(39665,)

In [19]:
X_test.shape

(9917,)

#web embedding

In [20]:
pip install gensim

Requirement already satisfied: gensim in c:\programdata\anaconda3\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\programdata\anaconda3\lib\site-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in c:\programdata\anaconda3\lib\site-packages (from gensim) (1.15.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\programdata\anaconda3\lib\site-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in c:\programdata\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
import gensim.downloader as api
import numpy as np

In [22]:
glove_model=api.load("glove-wiki-gigaword-100")

In [23]:
glove_model["good"]

array([-0.030769 ,  0.11993  ,  0.53909  , -0.43696  , -0.73937  ,
       -0.15345  ,  0.081126 , -0.38559  , -0.68797  , -0.41632  ,
       -0.13183  , -0.24922  ,  0.441    ,  0.085919 ,  0.20871  ,
       -0.063582 ,  0.062228 , -0.051234 , -0.13398  ,  1.1418   ,
        0.036526 ,  0.49029  , -0.24567  , -0.412    ,  0.12349  ,
        0.41336  , -0.48397  , -0.54243  , -0.27787  , -0.26015  ,
       -0.38485  ,  0.78656  ,  0.1023   , -0.20712  ,  0.40751  ,
        0.32026  , -0.51052  ,  0.48362  , -0.0099498, -0.38685  ,
        0.034975 , -0.167    ,  0.4237   , -0.54164  , -0.30323  ,
       -0.36983  ,  0.082836 , -0.52538  , -0.064531 , -1.398    ,
       -0.14873  , -0.35327  , -0.1118   ,  1.0912   ,  0.095864 ,
       -2.8129   ,  0.45238  ,  0.46213  ,  1.6012   , -0.20837  ,
       -0.27377  ,  0.71197  , -1.0754   , -0.046974 ,  0.67479  ,
       -0.065839 ,  0.75824  ,  0.39405  ,  0.15507  , -0.64719  ,
        0.32796  , -0.031748 ,  0.52899  , -0.43886  ,  0.67405  ,
        0.42136  , -0.11981  , -0.21777  , -0.29756  , -0.1351   ,
        0.59898  ,  0.46529  , -0.58258  , -0.02323  , -1.5442   ,
        0.01901  , -0.015877 ,  0.024499 , -0.58017  , -0.67659  ,
       -0.040379 , -0.44043  ,  0.083292 ,  0.20035  , -0.75499  ,
        0.16918  , -0.26573  , -0.52878  ,  0.17584  ,  1.065    ],
      dtype=float32)

In [24]:
def sentence_vector(sentence):
    
    vectors = []
    
    for word in sentence:
        
        if word in glove_model:
            vectors.append(glove_model[word])
    
    if len(vectors) == 0:
        return np.zeros(100)
    
    return np.mean(vectors, axis=0)

In [25]:
X_train_vectors = np.array(
    X_train.apply(sentence_vector).tolist()
)

In [26]:
X_test_vectors = np.array(
    X_test.apply(sentence_vector).tolist()
)

In [27]:
X_train_vectors.shape
X_test_vectors.shape

(9917, 100)

nural

In [28]:
pip install torch

Collecting torchNote: you may need to restart the kernel to use updated packages.

  Using cached torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: filelock in c:\programdata\anaconda3\lib\site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\programdata\anaconda3\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: setuptools<82 in c:\programdata\anaconda3\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\programdata\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\programdata\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\programdata\anaconda3\lib\site-packages (from torch) (2025.3.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Downloading torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.8/114.6 MB 1.6 MB/s eta 0:01:13
   ---------------------------------------- 1.0/114.6 MB 1.7 MB/s eta 0:01:08
    --------------------------------------- 1.6/114.6 MB 1.8 MB/s eta 0:01:02
    --------------------------------------- 1.8/114.6 MB 1.8 MB/s eta 0:01:03
    --------------------------------------- 1.8/114.6 MB 1.8 MB/s eta 0:01:03
    --------------------------------------- 2.4/114.6 MB 1.6 MB/s eta 0:01:10
   - -------------------------------------- 2.9/114.6 MB 1.7 MB/s eta 0:01:08
   - -------------------------------------- 3.4/114.6 MB 1.7 MB/s eta 0:01:05
   - -------------------------------------- 3.7/114.6 MB 1.7 MB/s eta 0:01:06
   - -------------------------------------- 3.7/114.6 MB 1.7 MB/s eta 0:01:06
   - -------------------------------------- 3.7/114.6 MB 1.7 MB/s eta 0:01:06
   - -------------------------------------- 4.2/114.6 MB 1.6 MB/s eta 0:01:11
   - -------------------------------------- 4.5/114.6 MB 1.5 MB/s eta 0:01:16
   - -------------------------------------- 4.7/114.6 MB 1.5 MB/s eta 0:01:15
   - -------------------------------------- 4.7/114.6 MB 1.5 MB/s eta 0:01:15
   - -------------------------------------- 5.2/114.6 MB 1.5 MB/s eta 0:01:16
   - -------------------------------------- 5.5/114.6 MB 1.4 MB/s eta 0:01:17
   - -------------------------------------- 5.5/114.6 MB 1.4 MB/s eta 0:01:17
   - -------------------------------------- 5.5/114.6 MB 1.4 MB/s eta 0:01:17
   -- ------------------------------------- 5.8/114.6 MB 1.3 MB/s eta 0:01:24
   -- ------------------------------------- 6.3/114.6 MB 1.3 MB/s eta 0:01:22
   -- ------------------------------------- 6.6/114.6 MB 1.3 MB/s eta 0:01:22
   -- ------------------------------------- 6.8/114.6 MB 1.3 MB/s eta 0:01:21
   -- ------------------------------------- 7.3/114.6 MB 1.4 MB/s eta 0:01:19
   -- ------------------------------------- 7.3/114.6 MB 1.4 MB/s eta 0:01:19
   -- ------------------------------------- 7.9/114.6 MB 1.4 MB/s eta 0:01:19
   -- ------------------------------------- 8.1/114.6 MB 1.4 MB/s eta 0:01:18
   -- ------------------------------------- 8.4/114.6 MB 1.4 MB/s eta 0:01:17
   -- ------------------------------------- 8.4/114.6 MB 1.4 MB/s eta 0:01:17
   -- ------------------------------------- 8.4/114.6 MB 1.4 MB/s eta 0:01:17
   -- ------------------------------------- 8.4/114.6 MB 1.4 MB/s eta 0:01:17
   -- ------------------------------------- 8.4/114.6 MB 1.4 MB/s eta 0:01:17
   --- ------------------------------------ 8.7/114.6 MB 1.2 MB/s eta 0:01:29
   --- ------------------------------------ 8.9/114.6 MB 1.2 MB/s eta 0:01:29
   --- ------------------------------------ 8.9/114.6 MB 1.2 MB/s eta 0:01:29
   --- ------------------------------------ 9.2/114.6 MB 1.2 MB/s eta 0:01:30
   --- ------------------------------------ 9.4/114.6 MB 1.2 MB/s eta 0:01:29
   --- ------------------------------------ 9.7/114.6 MB 1.2 MB/s eta 0:01:29
   --- ------------------------------------ 9.7/114.6 MB 1.2 MB/s eta 0:01:29
   --- ------------------------------------ 9.7/114.6 MB 1.2 MB/s eta 0:01:29
   --- ------------------------------------ 9.7/114.6 MB 1.2 MB/s eta 0:01:29
   --- ------------------------------------ 10.0/114.6 MB 1.1 MB/s eta 0:01:37
   --- ------------------------------------ 10.0/114.6 MB 1.1 MB/s eta 0:01:37
   --- ------------------------------------ 10.2/114.6 MB 1.1 MB/s eta 0:01:38
   --- ------------------------------------ 10.5/114.6 MB 1.1 MB/s eta 0:01:37
   --- ------------------------------------ 10.5/114.6 MB 1.1 MB/s eta 0:01:37
   --- ------------------------------------ 10.7/114.6 MB 1.1 MB/s eta 0:01:38
   --- ------------------------------------ 11.0/114.6 MB 1.1 MB/s eta 0:01:38
   --- ------------------------------------ 11.3/114.6 MB 1.1 MB/s eta 0:01:38
   --- ------------------------------------ 11.3/114.6 MB 1.1 MB/s eta 0:01:38
   ---- ----------------------------------- 11.5/114.6 MB 1.0 MB/s eta 0:01:39
   ---- ----------------------------------- 11.8/114.6 MB 1.0 MB/s eta 0:01:39
   ---- ----------------------------------- 11.8/114.6 MB 1.0 MB/s eta 0:01:39
   ---- ----------------------------------- 12.1/114.6 MB 1.0 MB/s eta 0:01:39
   ---- ----------------------------------- 12.3/114.6 MB 1.0 MB/s eta 0:01:38
   ---- ----------------------------------- 12.6/114.6 MB 1.0 MB/s eta 0:01:38
   ---- ----------------------------------- 12.8/114.6 MB 1.0 MB/s eta 0:01:38
   ---- ----------------------------------- 12.8/114.6 MB 1.0 MB/s eta 0:01:38
   ---- ----------------------------------- 13.1/114.6 MB 1.0 MB/s eta 0:01:39
   ---- ----------------------------------- 13.1/114.6 MB 1.0 MB/s eta 0:01:39
   ---- ----------------------------------- 13.4/114.6 MB 1.0 MB/s eta 0:01:39
   ---- ----------------------------------- 13.6/114.6 MB 1.0 MB/s eta 0:01:39
   ---- ----------------------------------- 13.9/114.6 MB 1.0 MB/s eta 0:01:39
   ---- ----------------------------------- 14.2/114.6 MB 1.0 MB/s eta 0:01:38
   ---- ----------------------------------- 14.2/114.6 MB 1.0 MB/s eta 0:01:38
   ----- ---------------------------------- 14.4/114.6 MB 1.0 MB/s eta 0:01:39
   ----- ---------------------------------- 14.7/114.6 MB 1.0 MB/s eta 0:01:39
   ----- ---------------------------------- 14.7/114.6 MB 1.0 MB/s eta 0:01:39
   ----- ---------------------------------- 14.7/114.6 MB 1.0 MB/s eta 0:01:39
   ----- --------------------------------- 14.9/114.6 MB 993.1 kB/s eta 0:01:41
   ----- --------------------------------- 14.9/114.6 MB 993.1 kB/s eta 0:01:41
   ----- --------------------------------- 15.2/114.6 MB 988.0 kB/s eta 0:01:41
   ----- --------------------------------- 15.5/114.6 MB 987.5 kB/s eta 0:01:41
   ----- --------------------------------- 15.7/114.6 MB 991.6 kB/s eta 0:01:40
   ----- --------------------------------- 16.0/114.6 MB 994.9 kB/s eta 0:01:40
   ----- --------------------------------- 16.3/114.6 MB 999.4 kB/s eta 0:01:39
   ----- ---------------------------------- 16.5/114.6 MB 1.0 MB/s eta 0:01:38
   ----- ---------------------------------- 16.8/114.6 MB 1.0 MB/s eta 0:01:38
   ----- ---------------------------------- 17.0/114.6 MB 1.0 MB/s eta 0:01:37
   ------ --------------------------------- 17.3/114.6 MB 1.0 MB/s eta 0:01:37
   ------ --------------------------------- 17.6/114.6 MB 1.0 MB/s eta 0:01:36
   ------ --------------------------------- 17.8/114.6 MB 1.0 MB/s eta 0:01:36
   ------ --------------------------------- 18.1/114.6 MB 1.0 MB/s eta 0:01:36
   ------ --------------------------------- 18.1/114.6 MB 1.0 MB/s eta 0:01:36
   ------ --------------------------------- 18.4/114.6 MB 1.0 MB/s eta 0:01:36
   ------ --------------------------------- 18.6/114.6 MB 1.0 MB/s eta 0:01:36
   ------ --------------------------------- 18.9/114.6 MB 1.0 MB/s eta 0:01:35
   ------ --------------------------------- 19.1/114.6 MB 1.0 MB/s eta 0:01:35
   ------ --------------------------------- 19.4/114.6 MB 1.0 MB/s eta 0:01:34
   ------ --------------------------------- 19.4/114.6 MB 1.0 MB/s eta 0:01:34
   ------ --------------------------------- 19.7/114.6 MB 1.0 MB/s eta 0:01:34
   ------ --------------------------------- 19.9/114.6 MB 1.0 MB/s eta 0:01:34
   ------- -------------------------------- 20.2/114.6 MB 1.0 MB/s eta 0:01:34
   ------- -------------------------------- 20.4/114.6 MB 1.0 MB/s eta 0:01:33
   ------- -------------------------------- 20.7/114.6 MB 1.0 MB/s eta 0:01:33
   ------- -------------------------------- 21.0/114.6 MB 1.0 MB/s eta 0:01:32
   ------- -------------------------------- 21.2/114.6 MB 1.0 MB/s eta 0:01:32
   ------- -------------------------------- 21.5/114.6 MB 1.0 MB/s eta 0:01:31
   ------- -------------------------------- 21.8/114.6 MB 1.0 MB/s eta 0:01:31
   ------- -------------------------------- 21.8/114.6 MB 1.0 MB/s eta 0:01:31
   ------- -------------------------------- 22.0/114.6 MB 1.0 MB/s eta 0:01:31
   ------- -------------------------------- 22.0/114.6 MB 1.0 MB/s eta 0:01:31
   ------- -------------------------------- 22.3/114.6 MB 1.0 MB/s eta 0:01:32
   ------- -------------------------------- 22.3/114.6 MB 1.0 MB/s eta 0:01:32
   ------- -------------------------------- 22.5/114.6 MB 1.0 MB/s eta 0:01:32
   ------- -------------------------------- 22.5/114.6 MB 1.0 MB/s eta 0:01:32
   ------- -------------------------------- 22.8/114.6 MB 1.0 MB/s eta 0:01:32
   -------- ------------------------------- 23.1/114.6 MB 1.0 MB/s eta 0:01:32
   -------- ------------------------------- 23.3/114.6 MB 1.0 MB/s eta 0:01:31
   -------- ------------------------------- 23.6/114.6 MB 1.0 MB/s eta 0:01:31
   -------- ------------------------------- 23.6/114.6 MB 1.0 MB/s eta 0:01:31
   -------- ------------------------------ 23.9/114.6 MB 998.0 kB/s eta 0:01:31
   -------- ------------------------------ 23.9/114.6 MB 998.0 kB/s eta 0:01:31
   -------- ------------------------------ 23.9/114.6 MB 998.0 kB/s eta 0:01:31
   -------- ------------------------------ 23.9/114.6 MB 998.0 kB/s eta 0:01:31
   -------- ------------------------------ 23.9/114.6 MB 998.0 kB/s eta 0:01:31
   -------- ------------------------------ 23.9/114.6 MB 998.0 kB/s eta 0:01:31
   -------- ------------------------------ 23.9/114.6 MB 998.0 kB/s eta 0:01:31
   -------- ------------------------------ 24.1/114.6 MB 950.8 kB/s eta 0:01:36
   -------- ------------------------------ 24.1/114.6 MB 950.8 kB/s eta 0:01:36
   -------- ------------------------------ 24.1/114.6 MB 950.8 kB/s eta 0:01:36
   -------- ------------------------------ 24.4/114.6 MB 939.2 kB/s eta 0:01:37
   -------- ------------------------------ 24.4/114.6 MB 939.2 kB/s eta 0:01:37
   -------- ------------------------------ 24.4/114.6 MB 939.2 kB/s eta 0:01:37
   -------- ------------------------------ 24.6/114.6 MB 926.2 kB/s eta 0:01:38
   -------- ------------------------------ 24.9/114.6 MB 924.4 kB/s eta 0:01:37
   -------- ------------------------------ 24.9/114.6 MB 924.4 kB/s eta 0:01:37
   -------- ------------------------------ 24.9/114.6 MB 924.4 kB/s eta 0:01:37
   -------- ------------------------------ 25.2/114.6 MB 916.5 kB/s eta 0:01:38
   -------- ------------------------------ 25.2/114.6 MB 916.5 kB/s eta 0:01:38
   -------- ------------------------------ 25.4/114.6 MB 912.5 kB/s eta 0:01:38
   -------- ------------------------------ 25.7/114.6 MB 910.2 kB/s eta 0:01:38
   -------- ------------------------------ 25.7/114.6 MB 910.2 kB/s eta 0:01:38
   -------- ------------------------------ 26.0/114.6 MB 907.7 kB/s eta 0:01:38
   -------- ------------------------------ 26.0/114.6 MB 907.7 kB/s eta 0:01:38
   -------- ------------------------------ 26.2/114.6 MB 905.7 kB/s eta 0:01:38
   --------- ----------------------------- 26.5/114.6 MB 905.6 kB/s eta 0:01:38
   --------- ----------------------------- 26.5/114.6 MB 905.6 kB/s eta 0:01:38
   --------- ----------------------------- 26.7/114.6 MB 902.8 kB/s eta 0:01:38
   --------- ----------------------------- 26.7/114.6 MB 902.8 kB/s eta 0:01:38
   --------- ----------------------------- 27.0/114.6 MB 901.5 kB/s eta 0:01:38
   --------- ----------------------------- 27.3/114.6 MB 896.3 kB/s eta 0:01:38
   --------- ----------------------------- 27.3/114.6 MB 896.3 kB/s eta 0:01:38
   --------- ----------------------------- 27.5/114.6 MB 883.2 kB/s eta 0:01:39
   --------- ----------------------------- 27.5/114.6 MB 883.2 kB/s eta 0:01:39
   --------- ----------------------------- 27.5/114.6 MB 883.2 kB/s eta 0:01:39
   --------- ----------------------------- 27.8/114.6 MB 863.6 kB/s eta 0:01:41
   --------- ----------------------------- 27.8/114.6 MB 863.6 kB/s eta 0:01:41
   --------- ----------------------------- 28.0/114.6 MB 849.7 kB/s eta 0:01:42
   --------- ----------------------------- 28.3/114.6 MB 832.7 kB/s eta 0:01:44
   --------- ----------------------------- 28.3/114.6 MB 832.7 kB/s eta 0:01:44
   --------- ----------------------------- 28.6/114.6 MB 833.2 kB/s eta 0:01:44
   --------- ----------------------------- 28.6/114.6 MB 833.2 kB/s eta 0:01:44
   --------- ----------------------------- 28.8/114.6 MB 830.8 kB/s eta 0:01:44
   --------- ----------------------------- 28.8/114.6 MB 830.8 kB/s eta 0:01:44
   --------- ----------------------------- 29.1/114.6 MB 815.7 kB/s eta 0:01:45
   --------- ----------------------------- 29.1/114.6 MB 815.7 kB/s eta 0:01:45
   --------- ----------------------------- 29.4/114.6 MB 806.1 kB/s eta 0:01:46
   --------- ----------------------------- 29.4/114.6 MB 806.1 kB/s eta 0:01:46
   ---------- ---------------------------- 29.6/114.6 MB 809.2 kB/s eta 0:01:45
   ---------- ---------------------------- 29.6/114.6 MB 809.2 kB/s eta 0:01:45
   ---------- ---------------------------- 29.6/114.6 MB 809.2 kB/s eta 0:01:45
   ---------- ---------------------------- 29.9/114.6 MB 798.6 kB/s eta 0:01:47
   ---------- ---------------------------- 29.9/114.6 MB 798.6 kB/s eta 0:01:47
   ---------- ---------------------------- 29.9/114.6 MB 798.6 kB/s eta 0:01:47
   ---------- ---------------------------- 30.1/114.6 MB 771.2 kB/s eta 0:01:50
   ---------- ---------------------------- 30.1/114.6 MB 771.2 kB/s eta 0:01:50
   ---------- ---------------------------- 30.4/114.6 MB 765.3 kB/s eta 0:01:50
   ---------- ---------------------------- 30.7/114.6 MB 753.1 kB/s eta 0:01:52
   ---------- ---------------------------- 30.7/114.6 MB 753.1 kB/s eta 0:01:52
   ---------- ---------------------------- 30.9/114.6 MB 769.8 kB/s eta 0:01:49
   ---------- ---------------------------- 31.2/114.6 MB 770.5 kB/s eta 0:01:49
   ---------- ---------------------------- 31.5/114.6 MB 771.6 kB/s eta 0:01:48
   ---------- ---------------------------- 31.5/114.6 MB 771.6 kB/s eta 0:01:48
   ---------- ---------------------------- 31.7/114.6 MB 773.1 kB/s eta 0:01:48
   ---------- ---------------------------- 31.7/114.6 MB 773.1 kB/s eta 0:01:48
   ---------- ---------------------------- 31.7/114.6 MB 773.1 kB/s eta 0:01:48
   ---------- ---------------------------- 31.7/114.6 MB 773.1 kB/s eta 0:01:48
   ---------- ---------------------------- 32.0/114.6 MB 753.2 kB/s eta 0:01:50
   ---------- ---------------------------- 32.0/114.6 MB 753.2 kB/s eta 0:01:50
   ---------- ---------------------------- 32.2/114.6 MB 766.8 kB/s eta 0:01:48
   ----------- --------------------------- 32.5/114.6 MB 768.6 kB/s eta 0:01:47
   ----------- --------------------------- 32.8/114.6 MB 769.7 kB/s eta 0:01:47
   ----------- --------------------------- 32.8/114.6 MB 769.7 kB/s eta 0:01:47
   ----------- --------------------------- 33.0/114.6 MB 770.2 kB/s eta 0:01:46
   ----------- --------------------------- 33.3/114.6 MB 769.7 kB/s eta 0:01:46
   ----------- --------------------------- 33.3/114.6 MB 769.7 kB/s eta 0:01:46
   ----------- --------------------------- 33.3/114.6 MB 769.7 kB/s eta 0:01:46
   ----------- --------------------------- 33.6/114.6 MB 761.5 kB/s eta 0:01:47
   ----------- --------------------------- 33.8/114.6 MB 763.1 kB/s eta 0:01:46
   ----------- --------------------------- 34.1/114.6 MB 765.5 kB/s eta 0:01:46
   ----------- --------------------------- 34.3/114.6 MB 767.7 kB/s eta 0:01:45
   ----------- --------------------------- 34.6/114.6 MB 771.9 kB/s eta 0:01:44
   ----------- --------------------------- 34.9/114.6 MB 776.5 kB/s eta 0:01:43
   ------------ -------------------------- 35.4/114.6 MB 783.9 kB/s eta 0:01:41
   ------------ -------------------------- 35.7/114.6 MB 789.3 kB/s eta 0:01:40
   ------------ -------------------------- 35.9/114.6 MB 787.4 kB/s eta 0:01:40
   ------------ -------------------------- 36.2/114.6 MB 790.7 kB/s eta 0:01:40
   ------------ -------------------------- 36.7/114.6 MB 798.7 kB/s eta 0:01:38
   ------------ -------------------------- 37.0/114.6 MB 804.2 kB/s eta 0:01:37
   ------------ -------------------------- 37.5/114.6 MB 814.6 kB/s eta 0:01:35
   ------------ -------------------------- 37.7/114.6 MB 821.2 kB/s eta 0:01:34
   ------------- ------------------------- 38.3/114.6 MB 832.7 kB/s eta 0:01:32
   ------------- ------------------------- 38.5/114.6 MB 835.5 kB/s eta 0:01:31
   ------------- ------------------------- 39.1/114.6 MB 842.1 kB/s eta 0:01:30
   ------------- ------------------------- 39.1/114.6 MB 842.1 kB/s eta 0:01:30
   ------------- ------------------------- 39.1/114.6 MB 842.1 kB/s eta 0:01:30
   ------------- ------------------------- 40.1/114.6 MB 863.2 kB/s eta 0:01:27
   ------------- ------------------------- 40.4/114.6 MB 867.8 kB/s eta 0:01:26
   ------------- ------------------------- 40.9/114.6 MB 874.5 kB/s eta 0:01:25
   ------------- ------------------------- 40.9/114.6 MB 874.5 kB/s eta 0:01:25
   -------------- ------------------------ 41.2/114.6 MB 877.9 kB/s eta 0:01:24
   -------------- ------------------------ 41.2/114.6 MB 877.9 kB/s eta 0:01:24
   -------------- ------------------------ 41.2/114.6 MB 877.9 kB/s eta 0:01:24
   -------------- ------------------------ 41.2/114.6 MB 877.9 kB/s eta 0:01:24
   -------------- ------------------------ 41.2/114.6 MB 877.9 kB/s eta 0:01:24
   -------------- ------------------------ 41.4/114.6 MB 851.8 kB/s eta 0:01:26
   -------------- ------------------------ 41.7/114.6 MB 856.5 kB/s eta 0:01:26
   -------------- ------------------------ 41.9/114.6 MB 851.8 kB/s eta 0:01:26
   -------------- ------------------------ 42.2/114.6 MB 849.6 kB/s eta 0:01:26
   -------------- ------------------------ 42.5/114.6 MB 849.2 kB/s eta 0:01:25
   -------------- ------------------------ 42.5/114.6 MB 849.2 kB/s eta 0:01:25
   -------------- ------------------------ 42.5/114.6 MB 849.2 kB/s eta 0:01:25
   -------------- ------------------------ 42.7/114.6 MB 835.5 kB/s eta 0:01:26
   -------------- ------------------------ 42.7/114.6 MB 835.5 kB/s eta 0:01:26
   -------------- ------------------------ 43.0/114.6 MB 831.3 kB/s eta 0:01:27
   -------------- ------------------------ 43.0/114.6 MB 831.3 kB/s eta 0:01:27
   -------------- ------------------------ 43.3/114.6 MB 831.3 kB/s eta 0:01:26
   -------------- ------------------------ 43.3/114.6 MB 831.3 kB/s eta 0:01:26
   -------------- ------------------------ 43.5/114.6 MB 825.1 kB/s eta 0:01:27
   -------------- ------------------------ 43.8/114.6 MB 822.0 kB/s eta 0:01:27
   -------------- ------------------------ 43.8/114.6 MB 822.0 kB/s eta 0:01:27
   -------------- ------------------------ 44.0/114.6 MB 816.6 kB/s eta 0:01:27

In [29]:
import torch
import torch.nn as nn
import torch.optim as optim

In [30]:
X_train_tensor = torch.tensor(
    X_train_vectors,
    dtype=torch.float32
)

X_test_tensor = torch.tensor(
    X_test_vectors,
    dtype=torch.float32
)

In [32]:
y_train = y_train.map({
    'positive':1,
    'negative':0
})

y_test = y_test.map({
    'positive':1,
    'negative':0
})

In [33]:
y_train_tensor = torch.tensor(
    y_train.values,
    dtype=torch.float32
).view(-1,1)

y_test_tensor = torch.tensor(
    y_test.values,
    dtype=torch.float32
).view(-1,1)

In [34]:
class SentimentNN(nn.Module):

    def __init__(self):

        super(SentimentNN, self).__init__()

        self.fc1 = nn.Linear(100, 64)

        self.relu = nn.ReLU()

        self.fc2 = nn.Linear(64, 1)

        self.sigmoid = nn.Sigmoid()

    def forward(self, x):

        x = self.fc1(x)

        x = self.relu(x)

        x = self.fc2(x)

        x = self.sigmoid(x)

        return x

In [35]:
model = SentimentNN()

In [36]:
criterion = nn.BCELoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

In [39]:
print("X_train_tensor shape:")
print(X_train_tensor.shape)

print("X_test_tensor shape:")
print(X_test_tensor.shape)

print("y_train_tensor shape:")
print(y_train_tensor.shape)

print("y_test_tensor shape:")
print(y_test_tensor.shape)

print("Model Architecture:")
print(model)

print("Loss Function:")
print(criterion)

print("Optimizer:")
print(optimizer)

X_train_tensor shape:
torch.Size([39665, 100])
X_test_tensor shape:
torch.Size([9917, 100])
y_train_tensor shape:
torch.Size([39665, 1])
y_test_tensor shape:
torch.Size([9917, 1])
Model Architecture:
SentimentNN(
  (fc1): Linear(in_features=100, out_features=64, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=64, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)
Loss Function:
BCELoss()
Optimizer:
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)